### ISSUE TITLE
Fix pairing issues with switch version 12+

### ISSUE THREAD

**Issue by Victrid** [Victrid/splatplost#10]
The plotter cannot be connected with switch for version 12+. 

**Behaviour**
When program is running to "Open the pairing menu on switch.", after the pairing menu is opened, the program cannot connect correctly.

**Problem**
This is caused due to broken dependency joycontrol.

**This issue is posted in order to replace:**

- https://github.com/Victrid/splatplost/issues/7
- https://github.com/Victrid/splatplost/issues/9

No new issues on pairing will be handled if it's the same behaviour until this issue is solved.

**Comment by SuperOkazaki** [comment]
Has upstream joycontrol found a solution for the pairing problem, or is this an issue that needs to be solved from scratch? Thank you for your work by the way.

**Comment by Victrid** [comment]
> Has upstream joycontrol found a solution for the pairing problem, or is this an issue that needs to be solved from scratch? Thank you for your work by the way.

@SuperOkazaki I see some fork of upstream joycontrol library may have a solution, while it might be not as compatible as the original one. Maybe this need to be somehow altered to use.

**Comment by SuperOkazaki** [comment]
> @SuperOkazaki I see some fork of upstream joycontrol library may have a solution, while it might be not as compatible as the original one. Maybe this need to be somehow altered to use.

Gotcha. Regular joycontrol is broken for the obvious reason, but while NXBT’s interface seems to be broken (out of date dependencies and broken on Python >=3.10) its actual bluetooth connection code works. I can’t get NXBT’s interface to function but I was able to get its controller demo working on my 14.0.1 Nintendo Switch, so maybe you can look at their code to see how they’re accomplishing it.

**Comment by Victrid** [comment]
I've adopted NXBT's controlling interface, and is now running some tests. After testing finished i'll push it and let you now.
