### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'input'

### ISSUE THREAD

**Issue by TattlingElk** [Victrid/splatplost#16]
might just be an idiot. But trying to get it working on Ubuntu
But no matter what I input I get the error.

Traceback (most recent call last):

  File "/usr/local/bin/splatplan", line 37, in <module>

    main(args.input, args.output)

AttributeError: 'Namespace' object has no attribute 'input'

**Comment by Victrid** [comment]
That's my linter's fault. I'll fix it now

**Comment by TattlingElk** [comment]
Really appreciate the work you are doing. You are a blessing tbh.

**Comment by Victrid** [comment]
I think this issue is done with version 0.1.2.
