### ISSUE TITLE
Another "Open the pairing menu on switch" but nothing happened

### ISSUE THREAD

**Issue by MagicLoki** [Victrid/splatplost#22]
![20220901_234051](https://user-images.githubusercontent.com/43291053/187956017-35382691-00d9-418f-b275-b14a49dd39ff.jpg)

After long waiting, it shows an exception.

`Exception in thread Thread-1 (connection_reset_watchdog):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/libnxctrl/nxbt/nxbt/controller/server.py", line 308, in connection_reset_watchdog
    paths = self.bt.find_connected_devices(alias_filter="Nintendo Switch")
  File "/usr/local/lib/python3.10/dist-packages/libnxctrl/nxbt/nxbt/bluez.py", line 906, in find_connected_devices
    device_conn_status = device_props.Get(
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownObject: Method "Get" with signature "ss" on interface "org.freedesktop.DBus.Properties" doesn't exist
`

NS version: 14.1.2
Ubuntu version: 22.04.1 LTS
Does this have something to do with me not having NXBT installed separately?
But when I try to install NXBT, it just failed to build the wheel for dbus-python
I have no idea about what to do next

**Comment by MagicLoki** [comment]
with `sudo apt-get install libdbus-1-dev libdbus-glib-1-dev` I successfully installed nxbt but still to no avail

**Comment by Victrid** [comment]
What is your configuration on VMWare and bluetooth adapter? It looks like that switch found you but refuses to connect

**Comment by MagicLoki** [comment]
I selected "Share Bluetooth devices with (Windows/Linux)", but I'm not sure what should I do to the bluetooth adapter.
![O(EG 2571} }VWAFRQE8DGW](https://user-images.githubusercontent.com/43291053/188059182-c8fc5b75-b7f6-4bb2-a413-0adf78b060bc.png)

In addition to that, I've once tried to get the NS to connect with the PC via bluetooth and have the PC act as a loudspeaker. The PC showed that the connection was successful, but the NS showed that it failed, so I gave up. After that, there is a bluetooth connection record of NS on the PC.

I don't know if this has any effect.

**Comment by MagicLoki** [comment]
Now I delete the bluetooth connection record in PC. Then the NS can't be found in Ubuntu.
I totally have no idea about how Ubuntu connect NS through external physical computer.

**Comment by 9hp** [comment]
I have the same issue.


NXBT connects to my switch on Virtual box (through  a vagrant install)


But has problems when I use VMWare so perhaps there's a setting were missing

**Comment by Victrid** [comment]
Hello,

I've created an image allowing you to reboot into. It has all dependencies configured and easy to use.

[Use image](https://github.com/Victrid/splatplost/blob/master/docs/image.md)
[Use image zh-CN](https://github.com/Victrid/splatplost/blob/master/docs/image.zh-CN.md)
