### ISSUE TITLE
The painting is too slow.....

### ISSUE THREAD

**Issue by chenchenfang** [Victrid/splatplost#26]
i use `sudo splatplot -- order` to draw.
It takes about 3 hours
![84461662441593_ pic](https://user-images.githubusercontent.com/50065243/188552818-ff9a937d-0f5b-4a68-99e8-217f65a3b0d2.jpg)
Is there a way to speed up?

**Comment by Victrid** [comment]
Others complain that using a fast scheme will distroy their graffiti, and they are asking for a slower but more stable algorithm...

https://github.com/Victrid/splatplost/issues/19#issuecomment-1233927359

If you have a good bluetooth connection with switch which have no packet loss on the current scheme, you may use these options on splatplot:
To control how long it waits after every step:
```bash
sudo splatplot ... --delay_time_ms [number]
```

To control how long it presses:
```bash
sudo splatplot ... --press_duration_ms [number]
```

They both set to be 100ms and if your bluetooth NIC can handle, i. e. figure is not distorted, you may decrease them to 80 (from https://github.com/Victrid/splatplost/issues/19#issuecomment-1234168029) or lower.

It may still takes around 2 hours to plot. This works like embroidery, not painting the ground ;)

**Comment by chenchenfang** [comment]
thinks.and it has been destroyed my graffiti....
maybe my Bluetooth quality is too poor
