### ISSUE TITLE
自动关闭画板 Automatic closing of the drawing board 

### ISSUE THREAD

**Issue by Sunosay** [Victrid/splatplost#27]
问题如下：程序连接完毕，设置完最小笔尖。坐标点会自动移到左上角，然后自动按-退出画板并重新进入，此时画笔重置为中等笔尖，并且坐标位于中间，开始作画

The problem： Program is connected .The coordinate point will automatically move to the upper left corner, then automatically press - to exit the board and re-enter, then the brush is reset to medium tip and the coordinates are in the middle, start painting

**Comment by Victrid** [comment]
Are you plotting it in splatoon 3? 

This might be duplicated with https://github.com/Victrid/splatplost/issues/28, as splatoon 2 use `-` to clear but splatoon 3 use `left stick press`

**Comment by Victrid** [comment]
Hello,
I've updated a beta version which supports splatoon 3 and have a GUI. Check https://github.com/Victrid/splatplost/tree/dev-v0.2 for readme file for more information.

If you want to try this version, you need to install with special pip command, which allows you to install a pre-release version:

```bash
sudo pip install splatplost==0.2.0.dev0
```

---

你好。
我已经更新了一个测试版，它支持Splatoon 3并有一个GUI。请查看 https://github.com/Victrid/splatplost/tree/dev-v0.2 上的自述文件，以了解用法。

如果你想尝试这个版本，你需要用特殊的 pip 命令来安装，它允许你安装预发布版本。

``bash
sudo pip install splatplost==0.2.0.dev0
```
