### ISSUE TITLE
Post closes before drawing

### ISSUE THREAD

**Issue by JusGman** [Victrid/splatplost#28]
The program works fine until it's about to start drawing, the controller presses the minus button causing it to save and exit.

**Comment by Victrid** [comment]
Hello, the Splatoon 3 is not currently supported and we are working on it!

**Comment by Victrid** [comment]
Hello, 
I've updated a beta version which supports splatoon 3 and have a GUI. Check https://github.com/Victrid/splatplost/tree/dev-v0.2 for readme file for more information.

If you want to try this version, you need to install with special pip command, which allows you to install a pre-release version:

```bash
sudo pip install splatplost==0.2.0.dev0
```
