### ISSUE TITLE
ModuleNotFoundError: No module named 'tqdm'

### ISSUE THREAD

**Issue by Charlie441324219** [Victrid/splatplost#3]
我已经安装了tqdm， 可是还是No module named 'tqdm'，这是为什么？

Laptop:~/Desktop/splatplost-master$ sudo python3 ./print.py IMAGE.order

Traceback (most recent call last):
  File "./print.py", line 6, in <module>
    import tqdm
ModuleNotFoundError: No module named 'tqdm'

Laptop:~/Desktop/splatplost-master$ pip3 install tqdm

Requirement already satisfied: tqdm in /home/.local/lib/python3.8/site-packages (4.59.0)

Laptop:~/Desktop/splatplost-master$ sudo python3 ./print.py IMAGE.order

Traceback (most recent call last):
  File "./print.py", line 6, in <module>
    import tqdm
ModuleNotFoundError: No module named 'tqdm'

**Comment by DaYu525** [comment]
Python相关库都装Python3版的   安装命令的  Python后面加上3就行    sudo apt-get install python3-tqdm

**Comment by Charlie441324219** [comment]
> sudo apt-get install python3-tqdm

problem solved thx
