### ISSUE TITLE
GUI not working without root privilege

### ISSUE THREAD

**Issue by Victrid** [Victrid/splatplost#31]
Using the 0.2.0.dev0 version, I get the GUI to launch (looks very nice by the way) and can interact with it, however when I click "Connect to Switch" and then "Start Pairing," nothing happens and the GUI does not progress to step 2. The Switch console, in the pairing menu, has no response either.
I'm not sure what I'm doing wrong-- I know my hardware is compatible with spoofing the controller because I have used NXBT before successfully on this setup.

I am using Python 3.10 on PopOS 22.04 LTS on bare metal, not in a VM.

_Originally posted by @SuperOkazaki in https://github.com/Victrid/splatplost/issues/13#issuecomment-1242833414_

**Comment by NotNite** [comment]
Heya, I'm having this issue, but running as root - is there any way I can see more descriptive logs of what's happening in my terminal? I'd love to use Splatplost for Splatoon 3 (mainly because it'll save me from writing my own :P) but journalctl is uninteresting and it seems the CLI was removed.

**Comment by NotNite** [comment]
I figured out my issue - I needed hciconfig installed.

**Comment by Victrid** [comment]
> I figured out my issue - I needed hciconfig installed.

It seems that the detection from CLI is not shown. I'll fix it.

> Heya, I'm having this issue, but running as root - is there any way I can see more descriptive logs of what's happening in my terminal? I'd love to use Splatplost for Splatoon 3 (mainly because it'll save me from writing my own :P) but journalctl is uninteresting and it seems the CLI was removed.

Let me see if I can add log.

**Comment by Victrid** [comment]
This issue is fixed in version 0.2.0.dev2. Check https://github.com/Victrid/splatplost/issues/13#issuecomment-1243287221.
