### ISSUE TITLE
Preconfigured image needs password to login

### ISSUE THREAD

**Issue by Nijuu20** [Victrid/splatplost#35]

**Comment by Victrid** [comment]
The password is `splatplost`, I forget to add it in the docs.

**Comment by Nijuu20** [comment]
> 

Also remember to add about close sleepmode in Arch Linux Setting because it may cause drawing tearing problems, don't know the reason how it does though.
Better to ensure the system activating when drawing.

**Comment by Victrid** [comment]
Let me see if I can disable it when building the image.
