### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by shenghejun** [Victrid/splatplost#39]
i use this command "sudo splatplan -i 1.jpeg  -o 111"
then 

Traceback (most recent call last):
  File "/usr/local/bin/splatplan", line 9, in <module>
    from splatplost.generate_route import ResetPosition, divide_image, generate_block_visit, generate_order_file, find_nearest_reset_position, \
  File "/usr/local/lib/python3.8/dist-packages/splatplost/generate_route.py", line 98, in <module>
    def get_label(image: np.ndarray) -> tuple[np.ndarray, int]:
TypeError: 'type' object is not subscriptable

**Comment by Victrid** [comment]
Read this page: https://github.com/Victrid/splatplost/blob/master/docs/image.md
