### ISSUE TITLE
Joycontrol unable to connect with Switch update 12.0.0

### ISSUE THREAD

**Issue by DaYu525** [Victrid/splatplost#6]
It had been post [here](https://github.com/mart1nro/joycontrol/issues/104) and someone give a  [solution](https://github.com/mart1nro/joycontrol/pull/110). But I have no time to test whether it can work(just test once and not work), and if it can instead the joycontrol  directory in this repositories.

**Comment by Victrid** [comment]
Thanks for your notice!
We'll update the code after the joycontrol library merging the patch.

**Comment by Victrid** [comment]
It looks like the original library hasn't been updated in a long time. 
We will now base the current library on the pull request you mentioned.

**Comment by Victrid** [comment]
I've tested the new fix, but encountered with some bluetooth issues.
The [issue](https://github.com/mart1nro/joycontrol/issues/104) mentioned this in the original repo says that it can still reconnect to switch if using reconnect address. After executing once our script should be able to using this reconnect address, so my current connection did not fail.
Before the final solution reached, please do not remove the `.reconnect` file.

**Comment by JackRBlack** [comment]
This is the first time I use this program. With the current problem, is it normal to see the following result with no pairing?

```bash
Open the pairing menu on switch.
[Errno 98] Address already in use
Fallback: Restarting bluetooth due to incompatibilities with the bluez "input" plugin. Disable the plugin to avoid issues. See https://github.com/mart1nro/joycontrol/issues/8
_
```

I guess the error mentioned above is caused because I'm using a bluetooth keyboard. But I think it can fix itself by restarting bluetooth, am I right?

**Comment by Victrid** [comment]
> This is the first time I use this program. With the current problem, is it normal to see the following result with no pairing?
> 
> ```shell
> Open the pairing menu on switch.
> [Errno 98] Address already in use
> Fallback: Restarting bluetooth due to incompatibilities with the bluez "input" plugin. Disable the plugin to avoid issues. See https://github.com/mart1nro/joycontrol/issues/8
> _
> ```
> 
> I guess the error mentioned above is caused because I'm using a bluetooth keyboard. But I think it can fix itself by restarting bluetooth, am I right?

The `restart` is done by the program. Your problem should lie in the `bluez` plugins. That's an infamous module and just randomly changes between updates breaking things. My earpods can never survive after updating. You could retry with the [original suggestion](https://github.com/mart1nro/joycontrol/issues/8), and with removing the `.reconnect` file if you have one. The address should be generated if it could not find the `.reconnect` file. 

That's not the problem here mentioned, and even if you passed your issue, the version 12 problem could not be solved currently. Switch needs to recognize the emulated controller (by the address) before updated to version 12+ to continue using it.

**Comment by patriziia** [comment]
[Someone](https://github.com/Poohl/joycontrol) solved the problem. I tested it on Pi 3B and worked perfectly. Maybe you can use this version to solve the problem.
https://github.com/mart1nro/joycontrol/pull/110

**Comment by DaYu525** [comment]
the repo [formatcom/joytransfer](https://github.com/formatcom/joytransfer) mentioned in [Poohl/joycontrol/issues/11](https://github.com/Poohl/joycontrol/issues/11) maybe worked

**Comment by andriusribas** [comment]
I tried to replace the files of the joycontrol folder with the ones from formatcom/joytransfer but it didn't work as it asks for a joycontrol.debug module. What am I doing wrong, which are the steps to get splatplost working?
