### ISSUE TITLE
Wasted my time

### ISSUE THREAD

**Issue by kibokura056** [Victrid/splatplost#7]
Running on Raspberry pi zero 2 w. Raspbian 32bit is installed.

After overcoming the hardships associated with dependencies, the program stuck at "Open the pairing menu on switch."
And my switch haven't recognized it.

**Comment by kibokura056** [comment]
Running on Raspberry pi zero 2 w. Raspbian 32bit is installed.

After overcoming the hardships associated with dependencies, the program stuck at "Open the pairing menu on switch."
And my switch not likely to recognize it.

**Comment by Victrid** [comment]
Hello, 
Your problem is addressed at https://github.com/Victrid/splatplost/issues/10. This will be fixed recently and please notice those issues for further updates.
I'll close this issue for now. If you have further problems, just reopen this issue.
