### ISSUE TITLE
"Open the pairing menu on switch" but nothing happened

### ISSUE THREAD

**Issue by FallenMeteorite** [Victrid/splatplost#9]
I opened the pairing menu but the script was responseless.
I run the script on Ubuntu in VWware, I don't know why it happens. 
Is it a problem of Bluetooth?

**Comment by Victrid** [comment]
Hello, 
Your problem is addressed at https://github.com/Victrid/splatplost/issues/10 and https://github.com/Victrid/splatplost/issues/11. This will be fixed recently and please notice those issues for further updates.
I'll close this issue for now.

**Comment by Victrid** [comment]
If you have further problems, just reopen this issue.
